use std::time::Duration;

use anyhow::Context as _;
use calloop::timer::Timer;
use smithay::backend::allocator::format::FormatSet;
use smithay::backend::allocator::gbm::GbmAllocator;
use smithay::backend::drm::compositor::{FrameFlags, PrimaryPlaneElement, RenderFrameError};
use smithay::backend::drm::exporter::gbm::GbmFramebufferExporter;
use smithay::backend::drm::output::{DrmOutput, DrmOutputRenderElements};
use smithay::backend::drm::{DrmDeviceFd, DrmError, DrmNode};
use smithay::backend::renderer::damage::Error as OutputDamageTrackerError;
use smithay::backend::renderer::glow::GlowRenderer;
use smithay::backend::renderer::multigpu::gbm::GbmGlesBackend;
use smithay::backend::renderer::multigpu::GpuManager;
use smithay::backend::renderer::ImportDma as _;
use smithay::backend::SwapBuffersError;
use smithay::desktop::utils::OutputPresentationFeedback;
use smithay::output::Output;
use smithay::reexports::drm;
use smithay::reexports::drm::control::atomic::AtomicModeReq;
use smithay::reexports::drm::control::{crtc, property, AtomicCommitFlags, Device as _};
use smithay::reexports::drm::control::connector;
use smithay::reexports::gbm::Format as DrmFourcc;
use smithay::reexports::wayland_protocols::wp::linux_dmabuf::zv1::server::zwp_linux_dmabuf_feedback_v1::TrancheFlags;
use smithay::reexports::wayland_protocols::wp::presentation_time::server::wp_presentation_feedback;
use smithay::reexports::wayland_server::backend::GlobalId;
use smithay::utils::Monotonic;
use smithay::wayland::dmabuf::DmabufFeedbackBuilder;
use smithay::wayland::presentation::Refresh;

use crate::backend::udev::UdevRenderer;
use crate::output::RedrawState;
use crate::renderer::{FhtRenderElement, OutputElementsResult};
use crate::state::{Fht, State, SurfaceDmabufFeedback};

/// The [`DrmOutput`] for a given [`Surface`].
/// This should be generated by a [`Device`](super::device::Device)'s [`DrmOutputManager`]
pub type SurfaceDrmOutput = DrmOutput<
    GbmAllocator<DrmDeviceFd>,
    GbmFramebufferExporter<DrmDeviceFd>,
    OutputPresentationFeedback,
    DrmDeviceFd,
>;

pub struct Surface {
    // Wayland output
    output: Output,
    output_global: GlobalId,
    // The render node for this surface.
    render_node: DrmNode,
    // The actual connector backing this surface.
    // Generally you would have these named `DP-n`, `HDMI-A-n`...
    connector: connector::Handle,
    crtc: crtc::Handle,

    drm_output: SurfaceDrmOutput,
    dmabuf_feedback: Option<SurfaceDmabufFeedback>,
    gamma_blob: Option<Box<dyn std::any::Any>>,
}

impl Surface {
    pub fn new(
        output: Output,
        output_global: GlobalId,
        render_node: DrmNode,
        connector: connector::Handle,
        crtc: crtc::Handle,
        drm_output: SurfaceDrmOutput,
        dmabuf_feedback: Option<SurfaceDmabufFeedback>,
    ) -> Self {
        Self {
            output,
            output_global,
            render_node,
            connector,
            crtc,
            drm_output,
            dmabuf_feedback,
            gamma_blob: None,
        }
    }

    /// The surface's [`Output`].
    pub fn output(&self) -> &Output {
        &self.output
    }

    /// The surface's [`Handle`](connector::Handle).
    pub fn connector(&self) -> &connector::Handle {
        &self.connector
    }

    /// The [`DrmNode`] that this surface uses for rendering.
    pub fn render_node(&self) -> DrmNode {
        self.render_node
    }

    /// The [`Fourcc`] format that this surface should use when doing copying.
    pub fn copy_format(&self) -> DrmFourcc {
        self.drm_output.format()
    }

    /// Reset this surface's compositor.
    ///
    /// Optionally also reset the swapchain if `reset_buffers` is set to `true`
    pub fn reset(&mut self, reset_buffers: bool) -> Result<(), DrmError> {
        self.drm_output.with_compositor(|compositor| {
            let res = compositor.reset_state();
            if reset_buffers {
                compositor.reset_buffers();
            }
            res
        })
    }

    /// Clear this surfacClear this surface
    pub fn clear(&mut self) -> Result<(), DrmError> {
        self.drm_output
            .with_compositor(|compositor| compositor.clear())
    }

    /// Initializes this surface's dmabuf feedback with a given `primary_node` as the main render
    /// node.
    pub fn init_dmabuf_feedback(
        &mut self,
        primary_render_node: DrmNode,
        gpu_manager: &mut GpuManager<GbmGlesBackend<GlowRenderer, DrmDeviceFd>>,
    ) -> anyhow::Result<()> {
        if self.dmabuf_feedback.is_some() {
            // NOTE: In fht-compositor, the primary render node never changes, so this function
            // should essentially be called either zero times (this surface node has been
            // initialized after the primary render node) or one time (the inverse, IE. before)
            return Ok(());
        }

        let primary_formats = gpu_manager
            .single_renderer(&primary_render_node)
            .context("Failed to get primary GPU renderer")?
            .dmabuf_formats();
        let render_formats = gpu_manager
            .single_renderer(&self.render_node)
            .context("Failed to get surface renderer")?
            .dmabuf_formats();

        let all_render_formats = primary_formats
            .iter()
            .chain(render_formats.iter())
            .copied()
            .collect::<FormatSet>();

        self.drm_output.with_compositor(|c| {
            let drm_surface = c.surface();
            let planes = drm_surface.planes().clone();

            // We limit the scan-out tranche to formats we can also render from
            // so that there is always a fallback render path available in case
            // the supplied buffer can not be scanned out directly
            let planes_formats = drm_surface
                .plane_info()
                .formats
                .iter()
                .copied()
                .chain(planes.overlay.into_iter().flat_map(|p| p.formats))
                .collect::<FormatSet>()
                .intersection(&all_render_formats)
                .copied()
                .collect::<FormatSet>();

            let builder = DmabufFeedbackBuilder::new(primary_render_node.dev_id(), primary_formats);
            let render_feedback = builder
                .clone()
                .add_preference_tranche(self.render_node.dev_id(), None, render_formats.clone())
                .build()
                .unwrap();

            let scanout_feedback = builder
                .add_preference_tranche(
                    drm_surface.device_fd().dev_id().unwrap(),
                    Some(TrancheFlags::Scanout),
                    planes_formats,
                )
                .add_preference_tranche(self.render_node.dev_id(), None, render_formats)
                .build()
                .unwrap();

            self.dmabuf_feedback = Some(SurfaceDmabufFeedback {
                render_feedback,
                scanout_feedback,
            });
        });

        Ok(())
    }

    /// Renders the following elements onto this surface's [`SurfaceDrmOutput`]
    pub fn render<'slf, 'render>(
        &'slf mut self,
        renderer: &mut super::UdevRenderer<'render>,
        output_elements: &OutputElementsResult<super::UdevRenderer<'render>>,
        // NOTE: This is only used when handling screencasting
        #[allow(unused)] target_presentation_time: Duration,
        frame_mode: FrameFlags,
        fht: &mut Fht,
    ) -> Result<bool, SwapBuffersError> {
        let res = self
            .drm_output
            .render_frame(
                renderer,
                &output_elements.elements,
                [0.1, 0.1, 0.1, 1.0],
                frame_mode,
            )
            .map_err(|err| -> SwapBuffersError {
                match err {
                    RenderFrameError::PrepareFrame(err) => SwapBuffersError::from(err),
                    RenderFrameError::RenderFrame(OutputDamageTrackerError::Rendering(err)) => {
                        SwapBuffersError::from(err)
                    }
                    _ => unreachable!(),
                }
            })?;

        if res.needs_sync() {
            if let PrimaryPlaneElement::Swapchain(element) = &res.primary_element {
                crate::profile_scope!("SyncPoint::wait");
                if let Err(err) = element.sync.wait() {
                    error!(?err, "Failed to wait for SyncPoint")
                };
            }
        }

        fht.update_primary_scanout_output(&self.output, &res.states);
        if let Some(dmabuf_feedback) = self.dmabuf_feedback.as_ref() {
            fht.send_dmabuf_feedbacks(&self.output, dmabuf_feedback, &res.states);
        }

        // Without damage = we just care that rendering happened.
        //
        // How we proceed with wlr-screencopy is when a client requests a without damage
        // frame, we queue rendering of the output to satisfy the request on
        // the next dispatch cycle
        fht.render_screencopy_without_damage(&self.output, renderer, output_elements);

        if !res.is_empty {
            // We have damage to submit, take presentation feedback try to queue the next
            // frame, this is the only code path where we should send frames to clients that
            // are displayed on the Surface's output.
            let presentation_feedback = fht.take_presentation_feedback(&self.output, &res.states);
            match self.drm_output.queue_frame(presentation_feedback) {
                Ok(()) => {
                    let output_state = fht.output_state.get_mut(&self.output).unwrap();
                    let new_state = RedrawState::WaitingForVblank { queued: false };
                    match std::mem::replace(&mut output_state.redraw_state, new_state) {
                        RedrawState::Queued => (),
                        RedrawState::WaitingForEstimatedVblankTimer {
                            token,
                            queued: true,
                        } => {
                            fht.loop_handle.remove(token);
                        }
                        _ => unreachable!(),
                    };

                    // We queued and client buffers are now displayed, we can now send
                    // frame events to them so they start building the next buffer
                    output_state.current_frame_sequence =
                        output_state.current_frame_sequence.wrapping_add(1);
                    // Also notify tracy of a new frame.
                    tracy_client::Client::running().unwrap().frame_mark();

                    // Damage also means screencast.
                    #[cfg(feature = "xdg-screencast-portal")]
                    {
                        fht.render_screencast_outputs(&self.output, renderer, &output_elements);
                        fht.render_screencast_windows(
                            &self.output,
                            renderer,
                            target_presentation_time,
                        );
                        fht.render_screencast_workspaces(
                            &self.output,
                            renderer,
                            target_presentation_time,
                        );
                    }
                    // And also screencopy.
                    fht.render_screencopy_with_damage(&self.output, renderer, &output_elements);

                    return Ok(true);
                }
                Err(err) => {
                    warn!("error queueing frame: {err}");
                }
            }
        }

        Ok(false)
    }

    /// Submits the last rendered frame.
    ///
    /// This should be called on v-blank events.
    pub fn submit(
        &mut self,
        refresh_interval: Duration,
        now: Duration,
        presentation_time: Duration,
        sequence: u64,
    ) -> anyhow::Result<()> {
        match self
            .drm_output
            .frame_submitted()
            .map_err(Into::<SwapBuffersError>::into)
        {
            Ok(Some(mut presentation_feedback)) => {
                // FIXME: ideally should be monotonically increasing for a surface.
                let mut flags = wp_presentation_feedback::Kind::Vsync
                    | wp_presentation_feedback::Kind::HwCompletion;

                let time = if presentation_time.is_zero() {
                    now
                } else {
                    flags.insert(wp_presentation_feedback::Kind::HwClock);
                    presentation_time
                };

                presentation_feedback.presented::<_, Monotonic>(
                    time,
                    Refresh::fixed(refresh_interval),
                    sequence,
                    flags,
                );
            }
            Ok(None) => (),
            Err(err) => {
                warn!("Error during rendering: {:?}", err);
                if let SwapBuffersError::ContextLost(err) = err {
                    panic!("Rendering loop lost: {}", err)
                }
            }
        };

        Ok(())
    }

    /// The [`Surface`]'s pending mode.
    pub fn pending_mode(&self) -> drm::control::Mode {
        self.drm_output.with_compositor(|c| c.pending_mode())
    }

    /// Sets the new [`Mode`](drm::control::Mode) for this surface.
    pub fn use_mode<'render>(
        &mut self,
        mode: drm::control::Mode,
        renderer: &mut UdevRenderer<'render>,
        render_elements: &'render DrmOutputRenderElements<
            UdevRenderer<'render>,
            FhtRenderElement<UdevRenderer<'render>>,
        >,
    ) -> anyhow::Result<()> {
        self.drm_output.use_mode(mode, renderer, render_elements)?;
        Ok(())
    }

    /// Whether this [`Surface`] has variable refresh rate enabled.
    pub fn vrr_enabled(&self) -> bool {
        self.drm_output.with_compositor(|c| c.vrr_enabled())
    }

    /// Whether this [`Surface`] has variable refresh rate enabled.
    pub fn set_vrr_enabled(&mut self, enabled: bool) -> anyhow::Result<()> {
        self.drm_output.with_compositor(|c| c.use_vrr(enabled))?;
        Ok(())
    }

    /// Get the gamma length of this surface.
    pub fn gamma_length(&self) -> anyhow::Result<usize> {
        self.drm_output.with_compositor(|compositor| {
            let surface = compositor.surface();
            let drm = surface.device_fd();
            let crtc_info = drm.get_crtc(self.crtc)?;
            anyhow::Result::Ok(crtc_info.gamma_length() as usize)
        })
    }

    /// Set the gamma values for this surface.
    pub fn set_gamma(&mut self, r: Vec<u16>, g: Vec<u16>, b: Vec<u16>) -> anyhow::Result<()> {
        let length = r.len();
        let expected = self.gamma_length()?;
        anyhow::ensure!(length != expected, "Gamma LUT mismatch");

        #[repr(C)]
        #[derive(Copy, Clone)]
        struct DrmColorLut {
            pub red: u16,
            pub green: u16,
            pub blue: u16,
            pub reserved: u16,
        }

        let mut lut = Vec::<DrmColorLut>::with_capacity(length);
        for i in 0..length {
            lut.push(DrmColorLut {
                red: r[i],
                green: g[i],
                blue: b[i],
                reserved: 0,
            });
        }

        let res = self.drm_output.with_compositor(|compositor| {
            let drm_surface = compositor.surface();
            let drm_device = drm_surface.device_fd();

            let blob_id = {
                use std::os::fd::AsRawFd;

                // Def of the IOCTL numbers (Linux standard)
                const DRM_IOCTL_BASE: u64 = 0x64; // 'd'
                const DRM_IOCTL_MODE_CREATE_BLOB_NR: u64 = 0xBD;

                let data = lut.as_slice();
                let length = (data.len() * std::mem::size_of::<DrmColorLut>()) as u32;

                let mut create_blob = drm_ffi::drm_mode_create_blob {
                    data: data.as_ptr() as usize as u64,
                    length,
                    blob_id: 0,
                };

                // Calculation of the IOCTL number (_IOWR)
                // This is the Rust translation of the C macro _IOWR('d', 0xBD, struct
                // drm_mode_create_blob)
                let ioctl_num = {
                    const _IOC_NRBITS: u64 = 8;
                    const _IOC_TYPEBITS: u64 = 8;
                    const _IOC_SIZEBITS: u64 = 14;
                    const _IOC_DIRBITS: u64 = 2;
                    const _IOC_NRSHIFT: u64 = 0;
                    const _IOC_TYPESHIFT: u64 = _IOC_NRSHIFT + _IOC_NRBITS;
                    const _IOC_SIZESHIFT: u64 = _IOC_TYPESHIFT + _IOC_TYPEBITS;
                    const _IOC_DIRSHIFT: u64 = _IOC_SIZESHIFT + _IOC_SIZEBITS;
                    const _IOC_READ: u64 = 2;
                    const _IOC_WRITE: u64 = 1;
                    const _IOC_INOUT: u64 = _IOC_READ | _IOC_WRITE;

                    let size = std::mem::size_of::<drm_ffi::drm_mode_create_blob>() as u64;

                    (_IOC_INOUT << _IOC_DIRSHIFT)
                        | ((size & ((1 << _IOC_SIZEBITS) - 1)) << _IOC_SIZESHIFT)
                        | (DRM_IOCTL_BASE << _IOC_TYPESHIFT)
                        | (DRM_IOCTL_MODE_CREATE_BLOB_NR << _IOC_NRSHIFT)
                };

                unsafe {
                    if libc::ioctl(drm_device.as_raw_fd(), ioctl_num, &mut create_blob) != 0 {
                        return Err(std::io::Error::last_os_error().into());
                    }
                }
                create_blob.blob_id
            };

            let blob = property::Value::Blob(blob_id.into());

            tracing::debug!("Gamma blob = {}", blob_id);

            let props = drm_device.get_properties(self.crtc)?;
            let (ids, vals) = props.as_props_and_values();

            let mut gamma_lut_id = None;
            let mut active_id = None;
            let mut mode_id = None;
            let mut degamma_id = None;
            let mut ctm_id = None;

            for (&id, &val) in ids.iter().zip(vals.iter()) {
                if let Ok(info) = drm_device.get_property(id) {
                    match info.name().to_str().unwrap_or("") {
                        "GAMMA_LUT" => gamma_lut_id = Some(id),
                        "ACTIVE" => active_id = Some((id, val)),
                        "MODE_ID" => mode_id = Some((id, val)),
                        "DEGAMMA_LUT" => degamma_id = Some((id, val)),
                        "CTM" => ctm_id = Some((id, val)),
                        _ => {}
                    }
                }
            }

            let gamma_lut_id = gamma_lut_id.context("This CRTC does not support gamma")?;
            let mut req = AtomicModeReq::new();
            req.add_property(
                self.crtc,
                gamma_lut_id,
                property::Value::Blob(blob_id.into()),
            );

            if let Some((id, v)) = degamma_id {
                if v != 0 {
                    req.add_property(self.crtc, id, property::Value::Blob(0u64));
                }
            }
            if let Some((id, v)) = ctm_id {
                if v != 0 {
                    req.add_property(self.crtc, id, property::Value::Blob(0u64));
                }
            }

            let first = drm_device.atomic_commit(AtomicCommitFlags::empty(), req.clone());

            if first.is_ok() {
                tracing::debug!("Gamma applied without modeset");
                return Ok(first.map(|_| blob));
            }

            tracing::debug!("Retrying with ALLOW_MODESET…");

            if let Some((id, _)) = active_id {
                req.add_property(self.crtc, id, property::Value::Boolean(true));
            }

            if let Some((id, v)) = mode_id {
                if v != 0 {
                    req.add_property(self.crtc, id, property::Value::Blob((v as u32).into()));
                }
            }

            for conn in drm_surface.current_connectors() {
                if let Ok(props) = drm_device.get_properties(conn) {
                    let (cids, cvals) = props.as_props_and_values();
                    for (&id, _) in cids.iter().zip(cvals.iter()) {
                        if let Ok(info) = drm_device.get_property(id) {
                            if info.name().to_str().unwrap_or("") == "CRTC_ID" {
                                req.add_property(conn, id, property::Value::CRTC(Some(self.crtc)));
                            }
                        }
                    }
                }
            }

            Ok(drm_device
                .atomic_commit(AtomicCommitFlags::ALLOW_MODESET, req)
                .map(|_| blob))
        });

        match res {
            Ok(blob) => {
                self.gamma_blob = Some(Box::new(blob));
                Ok(())
            }
            Err(err) => Err(err),
        }
    }

    /// Remove this surface.
    pub fn remove(mut self, fht: &mut Fht) {
        // Some clients might be slow to react. So before removing the global, we first mark it as
        // disabled, then 10 seconds after we actually proceed to remove it.
        fht.display_handle
            .disable_global::<State>(self.output_global.clone());
        let global = self.output_global.clone();
        let output = self.output.clone();
        _ = fht.loop_handle.insert_source(
            Timer::from_duration(Duration::from_secs(10)),
            move |_time, _, state| {
                let global = global.clone();
                state.fht.display_handle.remove_global::<State>(global);
                state.fht.remove_output(&output);
                calloop::timer::TimeoutAction::Drop
            },
        );

        _ = self.reset(true);
    }
}
